name: AppImage Release

on:
  workflow_call:
    secrets:
      DROPBOX_CLIENT_ID:
        required: true
      DROPBOX_SECRET:
        required: true

jobs:
  build:
    name: Build
    runs-on: Ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Add Dropbox secrets
        run: |
          # Create folder 'lib/services/dropbox' if needed
          mkdir -p lib/services/dropbox

          # Create file 'secrets.dart' and insert secrets
          echo "final identifier = '${{ secrets.DROPBOX_CLIENT_ID }}';" > lib/services/dropbox/secrets.dart
          echo "final secret = '${{ secrets.DROPBOX_SECRET }}';" >> lib/services/dropbox/secrets.dart
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.32.0
      - run: flutter upgrade
      - run: flutter config --enable-linux-desktop
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential pkg-config curl file git unzip xz-utils zip libgtk-3-dev
      - name: Build flutter app
        run: flutter build linux --release
      - name: Build AppImage using appimage-builder
        uses: docker://appimagecrafters/appimage-builder:latest
        with:
          entrypoint: appimage-builder
          args: --recipe ./AppImageBuilder.yml --skip-test
      - name: Save build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChessPositionsBinder-${{ github.ref_name }}-x86_64.AppImage
          path: "./*.AppImage*"
